server:
  port: 8015

spring:
  application:
    name: service1
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
  datasource:
    url: jdbc:h2:mem:JPATest2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true # H2 DB 웹콘솔 사용하도록 설정 (http://localhost:8080/h2-console)
      settings:
        web-allow-others: true
  jpa:
    database: H2
    show-sql: false # Jpa 수행 시 SQL문 로그 출력
    properties:
      hibernate:
        format_sql: true # 쿼리 출력시 포맷 정렬되도록 설정


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # 유레카 서비스에 (자신을) 등록 여부
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka.taskoo.net/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"


