apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: service1
  namespace: spring-boot-convention
spec:
  virtualhost:
    fqdn: service1.taskoo.net
  routes:
    - services:
        - name: service1
          port: 8015